# Generated by Django 5.0.4 on 2024-05-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="age",
            field=models.IntegerField(default=0, verbose_name="edad"),
        ),
        migrations.AddField(
            model_name="myuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
                verbose_name="genero",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="user_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.usertype",
            ),
        ),
    ]
