# Generated by Django 5.0.4 on 2024-08-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("jeepeta", "Jeepeta"),
                            ("camioneta", "Camioneta"),
                            ("deportivo", "Deportivo"),
                            ("sedan", "Sedán"),
                        ],
                        max_length=50,
                    ),
                ),
                ("year", models.IntegerField()),
            ],
        ),
    ]
