# Generated by Django 5.1 on 2024-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=50)),
                ('conditions', models.CharField(choices=[('jeepeta', 'Jeepeta'), ('camioneta', 'Camioneta'), ('deportivos', 'Deportivos'), ('sedan', 'sedan'), ('camion', 'Camion')], max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
