# Generated by Django 5.0.4 on 2024-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('car_type', models.CharField(choices=[('jepeta', 'Jepeta'), ('camioneta', 'Camioneta'), ('deportivo', 'Deportivo'), ('seldan', 'Selda')], max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
