# Generated by Django 5.1 on 2024-08-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_type',
        ),
    ]
