# Generated by Django 5.1 on 2024-08-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_car_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='conditions',
            new_name='CAR_TYPE',
        ),
    ]
